engines:
  rubocop:
    # NOTE: onkcop is not installed at codeclimate
    enabled: false

exclude_paths:
  - public/javascripts/bootstrap.js
  - public/javascripts/bootstrap.min.js
  - public/javascripts/jquery-ujs.js
  - public/javascripts/jquery.js
  - public/javascripts/npm.js
